"""change to create_date

Revision ID: 73bbb2173d7e
Revises: b4783e896935
Create Date: 2024-10-27 18:50:15.324305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bbb2173d7e'
down_revision = 'b4783e896935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.drop_column('charityproject', 'create_data')
    op.add_column('donation', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.drop_column('donation', 'create_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('create_data', sa.DATETIME(), nullable=True))
    op.drop_column('donation', 'create_date')
    op.add_column('charityproject', sa.Column('create_data', sa.DATETIME(), nullable=True))
    op.drop_column('charityproject', 'create_date')
    # ### end Alembic commands ###
